config/routes.rb
ActivityFinder::Application.routes.draw do
  devise_for :users

  post '/users/sign_in' => "home#index"

  root :to => "home#index"

  get '/users/profile' => "users#show"
  post '/search/' => "activities#locate"

  resources :categories, :only => [:show, :index]
  resources :users, :only => [:show]
  resources :activities
  resources :comments
  resources :memberships



end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :string(255)
#  address     :string(255)
#  longitude   :float
#  latitude    :float
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string(255)
#

class Activity < ActiveRecord::Base
  before_save :geocode
  has_many :memberships, :dependent => :destroy
  belongs_to :category
  has_many :users, :through => :memberships
  has_many :comments

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessible :address, :category_id, :description, :latitude, :longitude, :title

  validates_presence_of :address, :category_id, :description, :title

  def geocode
    #over API query limit fix
    # self.latitude = 32.3456
    # self.longitude = 141.4346

    result = Geocoder.search(self.address).first
      if result.present?
        self.latitude = result.latitude
        self.longitude = result.longitude
      end
  end

  def owner_name
    self.memberships.where(:role => 'owner').first.user.name
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :locate]
  before_filter :authorize_user, :only => [:edit, :update, :destroy]

  def create
    @activity = Activity.create(params[:activity])
    @membership = current_user.memberships.create(:activity_id => @activity.id, :role => 'owner')
    if @activity.save
      redirect_to @activity
    else
      render :new
    end
  end

  def index
    @activities = Activity.all
    @categories = Category.all
    cats = []

    @categories.each do |category|
      cats.push({
                  :id => category.id,
                  :title => category.title,
                  :activities => category.activities,
                  :image => category.image.url
      })
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { render :json => cats }
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @comments = @activity.comments
    @comment = Comment.new(:activity_id => params[:activity_id])
    @owner = @activity.owner_name
    # check to see if users are evident here
  end

  # def edit
  #   @activity = Activity.find_by_slug(params[:id])
  #   render 'edit'
  # end

  def update
    @activity = Activity.find_by_slug(params[:id])
    if @activity.update_attributes(params[:activity])
      redirect_to @activity
    else
      render 'edit'
    end
  end

  def destroy
    @activity = Activity.find_by_slug(params[:id])
    #check user is the only user remaining and also the owner
    if @activity.users == [current_user] && owner?
      @activity.destroy
      redirect_to root_path
      flash[:notice] = "You successfully deleted the activity"
    else
      redirect_to root_path
      flash[:notice] = "You cannot delete an activity whilst it has other members"
    end
  end

  def locate
    result = Geocoder.search(params[:address]).first
    if result.present?
      @latlong = [result.latitude, result.longitude]
      @categories = Category.all
      cats = []

      @categories.each do |category|
        cats.push({
                    :id => category.id,
                    :title => category.title,
                    :activities => category.activities,
                    :image => category.image.url
        })
      end

      respond_to do |format|
        format.json {
          render :json => {
            :latlong => @latlong,
            :cats => cats
          }
        }
      end
    else
      flash[:notice] = "Please enter a valid location"
      redirect_to root_path
    end
  end

  private

  def authorize_user
    @activity = Activity.find(params[:id])
    unless current_user.memberships.where(:activity_id => @activity.id).first.role == "owner"
      redirect_to @activity
      flash[:notice] = "You are not authorised to edit this activity"
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activities_show.html.haml
%h4= @activity.title
%p= @activity.description
%p= @activity.address


- if member? && owner?
  %p.edit_activity_button Edit Activity
  = button_to 'Delete Activity', activity_path(:activity_id => params[:id]), :method => :delete

- if member?
  = button_to 'Leave activity', membership_path(current_user.memberships.where(:activity_id => @activity).first), :method => :delete unless owner?
  %h4 Organiser
  %p= @owner

  %h4 Members
  %div.member_photos
    - @activity.users.each do |user|
      = image_tag user.image_url, :id => "actuserpic", :title => user.name

  %h4 Comments
  = render "comments/form", :locals => { :comment_parent => @comment }
  = render "comments/comments"

- else
  %p You need to be a member to see an activity.
  = button_to 'Join activity', memberships_path(:user_id => @user, :activity_id => @activity), :method => :post

app/views/activities/_all.html.erb
<%# @activities.each do |activity| %>
	<%#= activity.title %>
	<%#= activity.description %>
<%# end %>

app/views/activities/_editform.html.erb
<% if current_user %>
    <%= simple_form_for @activity do |f| %>
    <h2>EDIT AN ACTIVITY</h2><br><br>
          <div id="close">
        X
       </div>
        <%= f.input :title, :required => true, :autofocus => true, :placeholder => 'Name of the Activity: ' %>
        <%= f.input :description, :required => true, :placeholder => 'Description: ' %>
        <%= f.input :address, :required => true, :placeholder => 'Address: ' %>
        <%= f.association :category, :required => true %>
        <%= f.submit %>
    <% end %>
<% else %>
    <script type="text/javascript">
        if (window.location.pathname != '/') {
        window.location.href="/"
    };
    </script>
<% end %>

app/views/activities/_form.html.erb
<% if current_user %>
    <%= simple_form_for @activity do |f| %>
    <h2>CREATE AN ACTIVITY</h2><br><br>
          <div id="close">
        X
       </div>
        <%= f.input :title, :required => true, :autofocus => true, :placeholder => 'Name of the Activity: ' %>
        <%= f.input :description, :required => true, :placeholder => 'Description: ' %>
        <%= f.input :address, :required => true, :placeholder => 'Address: ' %>
        <%= f.association :category, :required => true %>
        <%= f.submit %>
    <% end %>
<% else %>
    <script type="text/javascript">
        if (window.location.pathname != '/') {
        window.location.href="/"
    };
    </script>
<% end %>

app/views/activities/_new.html.erb
<%= simple_form_for @activity do |f| %>
	<%= f.input :title, :required => true, :autofocus => true %>
	<%= f.input :description, :required => true %>
	<%= f.input :address, :required => true %>
	<%= f.association :category, :required => true %>
	<%= f.submit %>
<% end %>

app/views/activities/_search.html.erb
<%= text_field_tag :address, nil, :placeholder => 'SEARCH..', :required => true, :autofocus => true, :id => 'search_field' %>
<%= button_tag 'Search', :id => 'search_submit' %>

app/views/activities/edit.html.haml
%h4 Edit Activity
= render :partial => 'form'

app/views/activities/index.html.haml
%ul
- @activities.each do |activity|
	%li= link_to(activity.title, activity)

app/views/activities/new.html.haml
%h4 New Activity
= render :partial => 'form'

app/views/activities/show.html.haml
%div#map_float
  %div#map

%div#container
  %div#profilepic
    = image_tag(current_user.image, :id => 'ppic')
  %div#buttons
    %div#button1
      -if current_user.present?
        %p CREATE ACTIVITY
    %div#button2
      -if current_user.present?
        %p SHOW PROFILE
%div#panel
  - if current_user.present?
    = render 'activities_show'


%div#search
  = render 'activities/search'