config/routes.rb
ActivityFinder::Application.routes.draw do
  devise_for :users

  post '/users/sign_in' => "home#index"

  root :to => "home#index"

  get '/users/profile' => "users#show"
  post '/search/' => "activities#locate"

  resources :categories, :only => [:show, :index]
  resources :users, :only => [:show]
  resources :activities
  resources :comments
  resources :memberships



end

app/views/layouts/_intellinav.html.erb
<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
    	<%= link_to 'Home', root_path %>
      <%= link_to 'Create Activity', new_activity_path %>
	<%= link_to 'Activities', activities_path %>
	<%= link_to 'Edit profile', edit_user_registration_path %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path %> |
	<%= link_to "Login", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>ActivityFinder</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>
<%= csrf_meta_tags %>
</head>
<body>

	<% if user_signed_in? %>
		<div class="block_out hidden">
		</div>
	<% else %>
		<div class="block_out">
		</div>

		<div id="modal">
			<h1>Corral</h1>
			<br><br>
			<p>
			Welcome to Corral, a site which connects you with other people nearby who share the same interest. Whether you're looking for a regular walking buddy, someone who shares your passion for surf photography, or a group of people to exercise with, Corral will help put you in touch.
			</p>
			<br>
			<p>
			There's always people nearby who are looking to do the same things as you, but it's often hard to find them. Join Corral today and start something wonderful.
			</p>
			<br>
			<div class="login">
				<h2>LOG IN</h2>
			</div>
			<div class="signup">
				<h2>SIGN UP</h2>
			</div>
			<div id="close">
				X
			</div>
		</div>

		<div class="log_in hidden">
			<%= render :partial => 'devise/sessions/new' %>
		</div>

		<div class="sign_up hidden">
			<%= render :partial => 'devise/registrations/new' %>
		</div>

	<% end %>

	<% if user_signed_in? %>
	<% else %>
		<div id="loginbutt">
			<h2>LOGIN</h2>
		</div>

		<div id="signupbutt">
			<h2>SIGN UP</h2>
		</div>
	<% end %>

		<div class="new_activity hidden">
			<%= render :partial => 'activities/form' %>
		</div>

		<div class="edit_activity_button hidden">
			<%= render :partial => 'activities/form' %>
		</div>

		<div class="edit_user_button hidden">
			<%= render :partial => 'devise/registrations/edit' %>
		</div>

	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, id: "flash_#{name}" %>
	<% end %>

	<%= render :partial => 'activities/all', :locals => {:activities => @activities } %>

	<%= yield %>
</body>
</html>